### ISSUE TITLE
Protex plugin for jenkins crashing

### ISSUE THREAD

**Issue by gpsymantec** [blackducksoftware/protex-jenkins#2]
Protex plugin for Jenkins is crashing with following exception

d:\jenkins\workspace\snape_mainline_run_blackduck_protex
>exit 0 
ERROR: [ERROR] java.lang.NullPointerException
	at com.blackducksoftware.integration.protex.jenkins.PostBuildProtexScan.getProtexFacade(PostBuildProtexScan.java:554)
	at com.blackducksoftware.integration.protex.jenkins.PostBuildProtexScan.perform(PostBuildProtexScan.java:245)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

**Comment by utsavsanghani** [comment]
Hi,
Can you please provide some information about your environment? Px version, Jenkins version, Plugin version, type of code, network details, are you proxing in? how is the jenkins server behaving without the plugin?

**Comment by utsavsanghani** [comment]
Hi, 
Our internal tests with Protex 7.6 were successful when we tested. Can you please confirm if your Jenkins is working correctly without the Protex plugin?

Thanks!

**Comment by vinothkumar-e** [comment]
Hi,
    We are using Protex version is 7.6.0, jenkins version 1.645 and Protex Jenkins plugin version 1.4.1. 
Our source code is C++/VC++ compiled in VS2015 and we are not using any proxy configuration.
And our jenkins is working correctly without Protex plugin.  And also installed the protex client on jenkins VM and scanned the local source through protex client. The local source scan is working.

**Comment by vinothkumar-e** [comment]
Hi,
   Any update for this issue?

**Comment by utsavsanghani** [comment]
Can you share more details on this? Let me see if we can reproduce this. Thanks!

**Comment by utsavsanghani** [comment]
@vinothkumar-e , our QA team tried to reproduce this and were unsuccessful. They found it running successfully in their environment; pointing me to believe this is a problem within your environment. Given this is an open sourced implementation, this is the only level of support I can extend currently.

Thanks!
