### ISSUE TITLE
Error while scanning

### ISSUE THREAD

**Issue by gpsymantec** [blackducksoftware/protex-jenkins#7]
Started by user unknown or anonymous
[Office365connector] No webhooks to notify
Building remotely on Ubuntu Machine 10.7.135.246 in workspace /home/user/jenkins/workspace/Protex WebGoat Scan
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/WebGoat/WebGoat.git # timeout=10
Fetching upstream changes from https://github.com/WebGoat/WebGoat.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://github.com/WebGoat/WebGoat.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision e3e7ed004f9085457f5f442daeaae53f25389001 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e3e7ed004f9085457f5f442daeaae53f25389001
Commit message: "Not making a Docker release is we build develop (putting a tag will create a release which is more a controlled/intuitive way to make a release to Docker)"
 > git rev-list --no-walk e3e7ed004f9085457f5f442daeaae53f25389001 # timeout=10
[INFO] Getting Jdk on node  : Ubuntu Machine 10.7.135.246
[INFO] JDK home : /usr/lib/jvm/java-8-openjdk-amd64/jre
[INFO] Initializing - Protex Jenkins Plugin - 1.4.1
[INFO] -> Running on : ubuntu
[INFO] -> Using Url : <server_url>
[INFO] -> Using Username : user
[INFO] -> Using Protex Global TimeOut : 300
[INFO] -> Using Build Full Name : Protex WebGoat Scan #9
[INFO] -> Using Build Number : 9
[INFO] -> Using Build Workspace Path : /home/user/jenkins/workspace/Protex WebGoat Scan
[INFO] -> Using Protex Project Name : Jenkins-test
[INFO] -> Using Protex Source Path  : 
[INFO] -> Using Protex Scan Memory  : 2.0
[INFO] -> Using JDK : Java running slave agent at : /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
[INFO] -> Force Protex Full Scan : no
[INFO] The project 'Jenkins-test' exists.
[WARN] The Project : Jenkins-test, already exists! The scan will use the already exisiting Project.
[DEBUG] Source path exists at : /home/user/jenkins/workspace/Protex WebGoat Scan
[INFO] Starting Protex Scan...
[INFO] The project 'Jenkins-test' exists with Id: c_jenkins-test_6030
[INFO] Will scan with Java : /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
[INFO] Using this java for the command : /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
[INFO] Running Scan analyze command on /home/user/jenkins/workspace/Protex WebGoat Scan
[DEBUG] Command STATE : NEW
[INFO] 	--> OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

[INFO] 	--> java.lang.ClassNotFoundException: com.blackducksoftware.bdsclient.BDSClientDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.blackducksoftware.protex.plugin.BDSToolRemoteRunner.main(BDSToolRemoteRunner.java:58)

ERROR: [ERROR] Suppressed error : Command failed: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java, -classpath, /home/user/.jenkins/cache/jars/C6/61166FF987FDA9200977780F0BA2D0.jar, -XX:MaxPermSize=256m, -Xmx2048m, com.blackducksoftware.protex.plugin.BDSToolRemoteRunner, analyze, --expert-mode, --quiet, --server, <server_url>, --user, user, --password, *********, --log, /home/user/jenkins/workspace/Protex WebGoat Scan/BDSToolLog/bdstool.log, --no-new-project, --pure-project, c_jenkins-test_6030, --path, /home/user/jenkins/workspace/Protex WebGoat Scan, --porcelain
ERROR: [ERROR] java.lang.RuntimeException: Command failed: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java, -classpath, /home/user/.jenkins/cache/jars/C6/61166FF987FDA9200977780F0BA2D0.jar, -XX:MaxPermSize=256m, -Xmx2048m, com.blackducksoftware.protex.plugin.BDSToolRemoteRunner, analyze, --expert-mode, --quiet, --server, <server_url>, --user, user, --password, *********, --log, /home/user/jenkins/workspace/Protex WebGoat Scan/BDSToolLog/bdstool.log, --no-new-project, --pure-project, c_jenkins-test_6030, --path, /home/user/jenkins/workspace/Protex WebGoat Scan, --porcelain
	at com.blackducksoftware.protex.plugin.BlackDuckCommand$ForkedClientDriver.execute(BlackDuckCommand.java:415)
	at com.blackducksoftware.protex.plugin.BlackDuckCommand.run(BlackDuckCommand.java:128)
	at com.blackducksoftware.integration.protex.jenkins.ProtexScanner.runProtexScan(ProtexScanner.java:319)
	at com.blackducksoftware.integration.protex.jenkins.ProtexScanner.call(ProtexScanner.java:216)
	at com.blackducksoftware.integration.protex.jenkins.ProtexScanner.call(ProtexScanner.java:48)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

ERROR: [ERROR] BuildToolIntegrationException : null
ERROR: [ERROR] BuildToolIntegrationException : null
ERROR: [ERROR] com.blackducksoftware.integration.protex.exceptions.ProtexScannerException: BuildToolIntegrationException : null
	at com.blackducksoftware.integration.protex.jenkins.ProtexScanner.runProtexScan(ProtexScanner.java:342)
	at com.blackducksoftware.integration.protex.jenkins.ProtexScanner.call(ProtexScanner.java:216)
	at com.blackducksoftware.integration.protex.jenkins.ProtexScanner.call(ProtexScanner.java:48)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to Ubuntu Machine 10.7.135.246
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at com.blackducksoftware.integration.protex.jenkins.PostBuildProtexScan.perform(PostBuildProtexScan.java:346)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
		at hudson.model.Build$BuildExecution.post2(Build.java:186)
		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
		at hudson.model.Run.execute(Run.java:1819)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
Caused by: java.io.EOFException
	at com.blackducksoftware.protex.plugin.BDSToolSource.pump(BDSToolSource.java:200)
	at com.blackducksoftware.protex.plugin.BlackDuckCommand$ForkedClientDriver$ThreadPump.run(BlackDuckCommand.java:494)

Build step 'Protex - Create and Scan Actions' changed build result to UNSTABLE
[Office365connector] No webhooks to notify
Finished: UNSTABLE

**Comment by mj-mrityunjay** [comment]
I am also facing similar issue. Someone please help.

**Comment by stavvy-akamen** [comment]
@gpsymantec  and @mrityunjayk .  This is not an actively supported plugin and is no longer being developed, however I am curious if this started happening recently without any changes on your end?   Please mention me in reply (@akamen).

**Comment by gpsymantec** [comment]
This got fixed for me when we received Protex update. Upgrade your protex to 7.8.1

**Comment by stavvy-akamen** [comment]
Excellent!  Was hoping it was the underlying server that changed.  Thank you!
